name: CD api-lghctrp3

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Installing Node.js..."
      run: |
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: "Install dependencies"
      run: |
        git clone https://github.com/lahatra3/lahatra-gcp.git
        ls
        pwd
        cd lahatra-gcp && cd web-scrapping
        npm install
        ls
        pwd
        
    - name: "Run delivery"
      run: |
        pwd
        GMAIL_USER=${{ secrets.GMAIL_USER }} GMAIL_PASS=${{ secrets.GMAIL_PASS }} node src/main.js
