name: CI api

on:
  push:
    branches: [ "lahatra3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3        
    - name: "Installing Node.js..."
      run: |
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
        
    - name: "Install dependencies..."
      run: | 
        npm install -g @nestjs/cli
        cd api
        npm install
        npm test
    
    - name: "Merge to main !"
      uses: ridedott/merge-me-action@v2
      with:
        GITHUB_LOGIN: lahatra3
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
